export const JOB_DEFS = {
  soldier: {
    race: 'human',
    stats: { hp: 28, mp: 10, atk: 10, def: 8, mag: 4, res: 4, spd: 7 },
    moveRange: 3,
    abilities: ['attack', 'shieldbearer', 'rend-armor'],
    symbol: 'S',
  },
  whiteMage: {
    race: 'human',
    stats: { hp: 20, mp: 30, atk: 5, def: 5, mag: 9, res: 10, spd: 6 },
    moveRange: 3,
    abilities: ['attack', 'cure', 'protect'],
    symbol: 'W',
  },
  blackMage: {
    race: 'nu-mou',
    stats: { hp: 16, mp: 40, atk: 4, def: 4, mag: 12, res: 8, spd: 5 },
    moveRange: 3,
    abilities: ['attack', 'fire', 'thunder', 'blizzard'],
    symbol: 'B',
  },
  archer: {
    race: 'viera',
    stats: { hp: 22, mp: 12, atk: 9, def: 5, mag: 6, res: 6, spd: 9 },
    moveRange: 4,
    abilities: ['attack', 'aim', 'blind'],
    symbol: 'A',
  },
  thief: {
    race: 'human',
    stats: { hp: 20, mp: 16, atk: 8, def: 5, mag: 5, res: 5, spd: 11 },
    moveRange: 4,
    abilities: ['attack', 'steal', 'mug'],
    symbol: 'T',
  },
  fighter: {
    race: 'bangaa',
    stats: { hp: 32, mp: 8, atk: 13, def: 9, mag: 3, res: 3, spd: 6 },
    moveRange: 3,
    abilities: ['attack', 'powerbreak', 'shatter'],
    symbol: 'F',
  },
  paladin: {
    race: 'human',
    stats: { hp: 30, mp: 16, atk: 10, def: 11, mag: 7, res: 8, spd: 6 },
    moveRange: 3,
    abilities: ['attack', 'holy-blade', 'shieldbearer'],
    symbol: 'P',
  },
  ninja: {
    race: 'human',
    stats: { hp: 18, mp: 16, atk: 12, def: 4, mag: 5, res: 4, spd: 13 },
    moveRange: 4,
    abilities: ['attack', 'throw', 'shadowstitch'],
    symbol: 'N',
  },
  dragoon: {
    race: 'bangaa',
    stats: { hp: 34, mp: 8, atk: 14, def: 8, mag: 3, res: 3, spd: 7 },
    moveRange: 3,
    abilities: ['attack', 'jump'],
    symbol: 'D',
  },
  elementalist: {
    race: 'viera',
    stats: { hp: 18, mp: 36, atk: 4, def: 4, mag: 10, res: 9, spd: 7 },
    moveRange: 3,
    abilities: ['attack', 'flood', 'gust'],
    symbol: 'L',
  },
  redMage: {
    race: 'viera',
    stats: { hp: 22, mp: 28, atk: 8, def: 5, mag: 8, res: 7, spd: 8 },
    moveRange: 3,
    abilities: ['attack', 'fire', 'cure'],
    symbol: 'R',
  },
  timeMage: {
    race: 'nu-mou',
    stats: { hp: 14, mp: 38, atk: 3, def: 3, mag: 11, res: 9, spd: 5 },
    moveRange: 3,
    abilities: ['attack', 'slow', 'haste'],
    symbol: 'M',
  },
  summoner: {
    race: 'nu-mou',
    stats: { hp: 14, mp: 44, atk: 3, def: 3, mag: 13, res: 8, spd: 5 },
    moveRange: 3,
    abilities: ['attack', 'eidolon'],
    symbol: 'U',
  },
  illusionist: {
    race: 'human',
    stats: { hp: 16, mp: 40, atk: 4, def: 4, mag: 12, res: 7, spd: 5 },
    moveRange: 3,
    abilities: ['attack', 'phantasm'],
    symbol: 'I',
  },
  assassin: {
    race: 'viera',
    stats: { hp: 20, mp: 14, atk: 11, def: 5, mag: 6, res: 5, spd: 12 },
    moveRange: 4,
    abilities: ['attack', 'rockseal'],
    symbol: 'X',
  },
};

export function createUnit(id, job, ownerId, position) {
  const def = JOB_DEFS[job];
  return {
    id,
    ownerId,
    job,
    race: def.race,
    position,
    alive: true,
    hp: def.stats.hp,
    maxHp: def.stats.hp,
    mp: def.stats.mp,
    maxMp: def.stats.mp,
    stats: { ...def.stats },
    abilities: [...def.abilities],
    symbol: def.symbol,
    moved: false,
    acted: false,
    statusEffects: [],
  };
}
